sudo: false
language: java
jdk: oraclejdk8
before_install:
- chmod +x gradlew
install: ./gradlew assemble --refresh-dependencies
cache:
  directories:
  - $HOME/.gradle
deploy:
  provider: heroku
  buildpack: gradle
  app: smart-git
  api_key:
    secure: ZUgRvYaxTAxHdz5HWzvLUBPH2Q1i3nb0LuoLMpQ3F5IzMRy2VmEX4LsHCDEkqylJj8FhJFSJM39V1sai5c5i5yqgLbpd303wArib00NZNJP+YhTiB8kQIFVMmJ34vuGHhjqfUYRULWrV+5hjJPNdj+e8+dMWMhTf+g8Np0+8MebaqZ6dp5VLKyqxer4zvua9at98M0W7wnOCa/eCSv/Ap9RJQOACycD6AwCU3C17VsyLlb5DIpXuFyxZ03nhXE8sVMT3uq52yAGdd/98pn63ClMEhrTIcVVIpFoc+JxYN7KBiXfKANSdFigKWDhRMRXz7Zo9GOEVLqR+fr8KYC1kp0Dl/v+4/HrX/ONX+iihx7TZf7T/T45cNNqImz3HLgEITGWz10iNvTQhuPthKVxVOKFDPL6edKtP8fZvrCN2ieZUw8jDQnztG8MA1tYRHrdqJhvO54JygcT9lmqRN3UQ8duTql+XFsByKIqK0ApU+sseKkoOJvha7YFlhTvlraBUQSEm3B426GSt8iNX0a/r3qShZU4aFRastDe1WzJ/5/bqsx9S6Qsx3gVnbTFR/Hcz1SXwef9nyUDkDZBAM+4r0FvEd257tFCs7e8olbNd3vposYyJ8NGMq6L61UqX9oShx4ggdep6UpJemmg+kfZdpbWVoUA3r3Esu07eeQXHOx8=